services:
  viewer:
    image: wao-aw-server
    user: "1000:1000"
    ports:
      - '5600:5600'
    volumes: 
      - ${HOME}/.local/share/activitywatch:/home/awserver/.local/share/activitywatch
    command: aw-server --host 0.0.0.0
    tty: true
